### ISSUE TITLE
Power usage

### ISSUE THREAD

**Issue by BlackEdder** [Coopdis/easyMesh#11]
More asking for information than opening an issue, but any clue how much the power usage is of this setup? Say I wanted to run on batteries how long could I expect them to last?

Is it possible to setup a low power network, where nodes go in and out of sleep?

**Comment by sfranzyshen** [comment]
This question might be better handled by the esp8266 forum ...  http://www.esp8266.com/

as far as nodes going to sleep ... that would probably mess things up

**Comment by RudyFiero** [comment]
Issue should really be for code issues only. Feature requests, support, that kind of stuff belongs ... 
OK I don't know. 

So the esp8266 site is a reasonable option.

**Comment by sfranzyshen** [comment]
sorry ... by all means open an issue to request sleeping functionality ... but a generic question about how much power does your code use ... seams like a hardware question  ...
