### ISSUE TITLE
question: Get Telemetry from each Mesh Node

### ISSUE THREAD

**Issue by jaecktec** [Coopdis/easyMesh#19]
I haven't seen a way to get telemtry data (like signal strength and nodes in proximidity). Is there a way?

**Comment by BlackEdder** [comment]
There is no build in way to do this, but this can be done in your own code by scanning for APs.

An example that might get you started:
https://gitlab.com/BlackEdder/painlessMesh/blob/master/src/painlessMeshSTA.cpp#L124

By the way. I am not sure how active the easyMesh project is anymore. I am maintaining a fork here:
https://gitlab.com/BlackEdder/painlessMesh
that I plan to actively maintain. The fork also incorporates @sfranzyshen changes. I have plans to develop painlessMesh further, but that will depend on how much time I have.

EDIT: clarify I will be maintaining painlessMesh

**Comment by RudyFiero** [comment]
I'm going to try this as soon as I can.

**Comment by jaecktec** [comment]
Thank you! The AP way is quite unrelaible. (Antenna diversity and stuff,..) But thank you :)
Hope I can get the Raw Packets library set working and build a time of flight thingy...
