### ISSUE TITLE
EasyMesh vs PainlessMesh

### ISSUE THREAD

**Issue by AlexisTM** [Coopdis/easyMesh#40]
Hi there,

Who is the copy of whom? EasyMesh or PainlessMesh?

One is MIT, the other GPLv3, but it's almost the same codebase.

https://gitlab.com/BlackEdder/painlessMesh/blob/master/README.md

**Comment by NicksonYap** [comment]
PainlessMesh's Repo description says:
"A painless way to setup a mesh with ESP8266 and ESP32 devices. Based on https://github.com/Coopdis/easyMesh"

**Comment by danielcera** [comment]
I am working with PainlessMesh, but with more than 10 nodes it is something unstable, it will be that with easymesh I will achieve a better performance, or what is the difference between these two, thanks.

**Comment by AlexisTM** [comment]
@danielcera I guess the best way to know is to test.

Plus, if you report this to PainlessMesh, you can fix the problem at the source :)

This repo is on sleep mode unlike painlessMesh ;)

**Comment by julioj4pa** [comment]
@danielcera Is it unstable to send broadcast package and unicast package?

**Comment by AlexisTM** [comment]
Outdated.
