### ISSUE TITLE
Json object destroying data argument.

### ISSUE THREAD

**Issue by muratdemirtas** [Coopdis/easyMesh#8]
i found a bug in EasyMeshConnection:: 286. Received arguman data is destroying after json parsing and Adhoc messaging doesnt work. i created a new copy of data argument before json parsing. Bug starting with this lines.

```
DynamicJsonBuffer jsonBuffer( JSON_BUFSIZE );
JsonObject& root = jsonBuffer.parseObject( data );
```

After data argument is corrupted. tempStr is parsing wrong json data and sending to another node of mesh. In this case Adhoc message system doesnt work.

```
    case SINGLE:
      { // bla bla
            String tempStr( data );
            staticThis->sendPackage( staticThis->findConnection( (uint32_t)root["dest"] ), tempStr );
        }
```

//Corrupted data received in destination node
0x1 meshRecvCb: parseObject() failed. data=dest<--  
0x200   meshRecvCb(): data={"dest":23356,"from":1515899,"type":5,"subs":[{"chipId":1859811,"subs":[]}]} fromId=1515899
0x200   Recvd from 1515899-->dest<--                           //corrupted data.

And i created copy of the data and problem solved.

```
String kopya(data);      //copy data before json parsing

DynamicJsonBuffer jsonBuffer( JSON_BUFSIZE );
JsonObject& root = jsonBuffer.parseObject( data );
if (!root.success()) {   // Test if parsing succeeded.
    staticThis->debugMsg( ERROR, "meshRecvCb: parseObject() failed. data=%s<--\n", data);
    return;
}
```

and 

case SINGLE:
          { // bla bla

```
            staticThis->sendPackage( staticThis->findConnection( (uint32_t)root["dest"] ), kopya );
        }
```

//Adhoc side serial messages
0x200   Mesaj: This message from 1859811  to 23356 . Transporting..
Sending data : dest                       //using String tempStr(data)
Sending data2: {"dest":23356,"from":1859811,"type":9,"msg":"hello"}    //using String kopya(data); before json

//Destination nodemcu side serial message
0x200   receivedCallback():
0x200   Mesaj: This message for us..

**Comment by sholehhudin** [comment]
Thanks @muratdemirtas . this help me alot

**Comment by sfranzyshen** [comment]
Can anyone explain why this works?
this change has been added to https://github.com/sfranzyshen/easyMesh/tree/devel

**Comment by RudyFiero** [comment]
I am still having problems fully understanding "this" in code. Or do you mean a different "this". ;)

To be honest, all of this is above my head. But I am certainly willing to test this once you have something you want tested with more units. 

Right now my interest is in being able to connect to this network with a tablet, seamlessly. Much as you have described. I'm working on understanding more of the pieces to make that work, without getting too involved in the lower level code. Because this drives me crazy. :)

**Comment by sfranzyshen** [comment]
I meant why the fix @muratdemirtas posted works? just creating a String of data fixes data structure some how?

**Comment by BlackEdder** [comment]
> Right now my interest is in being able to connect to this network with a tablet, seamlessly. Much as you have described. I'm working on understanding more of the pieces to make that work, without getting too involved in the lower level code. Because this drives me crazy. :)

@RudyFiero I implemented a basic client (I want to use it on a raspberrypi) that only does the minimal needed to receive and send messages: https://github.com/BlackEdder/easyMesheD That might be a better starting point to understand how to connect a tablet.

**Comment by muratdemirtas** [comment]
@sfranzyshen because , memory leak in arduino json library.
